INSERT INTO RD_UNIDEF_ACCOUNTCONTACT (TABLE_NAME, FIELD_NAME, COLUMN_NAME, LABEL, HELPTEXT, UNIVERSE_NAME, UNIVERSE_FIELD_NAME, UNIVERSE_FIELD_NAME_OVERRIDE, INCLUDED, ORDERBY)
select rj_field.TABLE_NAME, rj_field.FIELD_NAME, rj_field.COLUMN_NAME, rj_field.LABEL, rj_field.HELPTEXT, 'U_ACCOUNT_CONTACT', SYS_TRANSLATE(rj_field.label,' -?/\():;.','_____________'), NULL, 'False', NULL
from rj_field 
where rj_field.table_name in (get_table_name('account'), get_table_name('RC_BIOS__ACCOUNT_ADDRESS__c'))
AND CONCAT(rj_field.TABLE_NAME, rj_field.FIELD_NAME, rj_field.COLUMN_NAME, rj_field.LABEL)
NOT IN (SELECT CONCAT(VD.TABLE_NAME, VD.FIELD_NAME, VD.COLUMN_NAME, VD.LABEL) FROM RD_UNIDEF_ACCOUNTCONTACT VD);

INSERT INTO RD_UNIDEF_ACCOUNTCONTACT (TABLE_NAME, FIELD_NAME, COLUMN_NAME, LABEL, HELPTEXT, UNIVERSE_NAME, UNIVERSE_FIELD_NAME, UNIVERSE_FIELD_NAME_OVERRIDE, INCLUDED, ORDERBY)
select rj_field.TABLE_NAME, rj_field.FIELD_NAME, rj_field.COLUMN_NAME, CONCAT('Primary_', rj_field.LABEL), rj_field.HELPTEXT, 'U_ACCOUNT_CONTACT', concat(SYS_TRANSLATE(rj_field.label,' -?/\():;.','_____________'),'_Primary'), NULL, 'False', NULL
from rj_field 
where rj_field.table_name in (get_table_name('CONTACT'))
AND CONCAT(rj_field.TABLE_NAME, rj_field.FIELD_NAME, rj_field.COLUMN_NAME, CONCAT('Primary_', rj_field.LABEL))  
NOT IN (SELECT CONCAT(VD.TABLE_NAME, VD.FIELD_NAME, VD.COLUMN_NAME, VD.LABEL) FROM RD_UNIDEF_ACCOUNTCONTACT VD);

INSERT INTO RD_UNIDEF_ACCOUNTCONTACT (TABLE_NAME, FIELD_NAME, COLUMN_NAME, LABEL, HELPTEXT, UNIVERSE_NAME, UNIVERSE_FIELD_NAME, UNIVERSE_FIELD_NAME_OVERRIDE, INCLUDED, ORDERBY)
select rj_field.TABLE_NAME, rj_field.FIELD_NAME, rj_field.COLUMN_NAME, CONCAT('Secondary_', rj_field.LABEL), rj_field.HELPTEXT, 'U_ACCOUNT_CONTACT', CONCAT(SYS_TRANSLATE(rj_field.label,' -?/\():;.','_____________'),'_Secondary'), NULL, 'False', NULL
from rj_field where rj_field.table_name in (get_table_name('CONTACT'))
AND CONCAT(rj_field.TABLE_NAME, rj_field.FIELD_NAME, rj_field.COLUMN_NAME, CONCAT('Secondary_', rj_field.LABEL))
NOT IN (SELECT CONCAT(VD.TABLE_NAME, VD.FIELD_NAME, VD.COLUMN_NAME, VD.LABEL) FROM RD_UNIDEF_ACCOUNTCONTACT VD);
