DROP FUNCTION IF EXISTS GIVING_LAST_PAYMENT_DATE;
CREATE FUNCTION GIVING_LAST_PAYMENT_DATE(GIVINGID_IN VARCHAR(18)) RETURNS DATE
    DETERMINISTIC
BEGIN
     DECLARE LAST_PAYMENT_DATE DATE;
     SET LAST_PAYMENT_DATE = 
    (
      Select CLOSEDATE
        from V_opportunity o
        where RC_GIVING__PARENT = GIVINGID_IN
        AND STAGENAME IN ('COMPLETED', 'PARTIALLY COMPLETE')
        ORDER BY CLOSEDATE DESC
        LIMIT 1 
        );        
     RETURN LAST_PAYMENT_DATE;
    END;
