DROP FUNCTION IF EXISTS GIVING_PLEDGE_PAST_DUE_BALANCE;
CREATE FUNCTION GIVING_PLEDGE_PAST_DUE_BALANCE(GIVINGID_IN VARCHAR(18)) RETURNS DECIMAL(22,6)
    DETERMINISTIC
BEGIN
     DECLARE PAST_DUE_BALANCE DECIMAL(22,6);
     SET PAST_DUE_BALANCE = 
    (
      Select SUM(AMOUNT) - SUM(Rc_GIVING__CLOSE_DATE)
        from V_opportunity o
        where (id = GIVINGID_IN
        OR RC_GIVING__PARENT = GIVINGID_ID)
        and closedate <= curdate()
        );
     RETURN PAST_DUE_BALANCE;
    END;
