CREATE OR REPLACE VIEW O_SOLICITATION
AS
SELECT
       -- ACCOUNT AND CONTACT NUMBERS
        V_ACCOUNT.ID ACCOUNT_GUID,
        V_ACCOUNT.RC_BIOS__EXTERNAL_ID ACCOUNT_EXTERNAL_ID,
        V_ACCOUNT.RC_BIOS__PREFERRED_CONTACT PRIMARY_CONTACT_GUID,
        CONTACT_SECONDARY_GUID(V_ACCOUNT.ID) SECONDARY_CONTACT_GUID,
        -- ACCOUNT NAME AND ADDRESS INFO
        V_ACCOUNT.RC_BIOS__SALUTATION,
        S_PREFERRED_ADDRESS_BILLING.RC_BIOS__STREET_LINE_1,
        S_PREFERRED_ADDRESS_BILLING.RC_BIOS__STREET_LINE_2,
        S_PREFERRED_ADDRESS_BILLING.RC_BIOS__CITY,
        S_PREFERRED_ADDRESS_BILLING.RC_BIOS__STATE,
        S_PREFERRED_ADDRESS_BILLING.RC_BIOS__POSTAL_CODE,
        S_PREFERRED_ADDRESS_BILLING.RC_BIOS__COUNTRY,
        -- CONTACT NAMES
        V_CONTACT_P.SALUTATION PRIMARY_TITLE,
        V_CONTACT_P.FIRSTNAME PRIMARY_FIRSTNAME,
        V_CONTACT_P.RC_BIOS__MIDDLE_NAME PRIMARY_MIDDLENAME,
        V_CONTACT_P.LASTNAME PRIMARY_LASTNAME,
        SALUTATION_LINE_1_CONTACT(V_ACCOUNT.RC_BIOS__PREFERRED_CONTACT) PRIMARY_FULLNAME,
        V_CONTACT_S.SALUTATION SECONDARY_TITLE,
        V_CONTACT_S.FIRSTNAME SECONDARY_FIRSTNAME,
        V_CONTACT_S.RC_BIOS__MIDDLE_NAME SECONDARY_MIDDLENAME,
        V_CONTACT_S.LASTNAME SECONDARY_LASTNAME,
        SALUTATION_LINE_1_CONTACT(CONTACT_SECONDARY_GUID(V_ACCOUNT.ID)) SECONDARY_FULLNAME,
        V_ACCOUNT.RC_BIOS__PREFERRED_CONTACT_EMAIL PRIMARY_EMAIL,
        V_ACCOUNT.RC_BIOS__PREFERRED_CONTACT_PHONE PRIMARY_PHONE,
        -- GIVING SUMMARY INFORMATION
        V_RC_GIVING__SUMMARY.RC_GIVING__FIRST_GIVING_AMOUNT FIRST_GIVING_AMOUNT, 
        V_RC_GIVING__SUMMARY.RC_GIVING__FIRST_GIVING_DATE FIRST_GIVING_DATE,
        V_RC_GIVING__SUMMARY.RC_GIVING__CURRENT_RENEWAL_AMOUNT CURRENT_RENEWAL_AMOUNT,
        V_RC_GIVING__SUMMARY.RC_GIVING__CURRENT_ADDITIONAL_AMOUNT CURRENT_ADDITIONAL_AMOUNT,
        V_RC_GIVING__SUMMARY.RC_GIVING__GIVING_LEVEL_EXPIRATION_DATE EXPIRATION_DATE,
        V_RC_GIVING__SUMMARY.RC_GIVING__CURRENT_AMOUNT CURRENT_AMOUNT,
        V_RC_GIVING__SUMMARY.RC_GIVING__IS_MAJOR_GIVER MAJOR_DONOR,
        V_RC_GIVING__SUMMARY.RC_GIVING__IS_SUSTAINING_GIVER SUSTAINER,
        V_RC_GIVING__SUMMARY.RC_GIVING__MOST_RECENT_GIVING_AMOUNT MOST_RECENT_GIVING_AMOUNT,
        V_RC_GIVING__SUMMARY.RC_GIVING__MOST_RECENT_GIVING_DATE MOST_RECENT_GIVING_DATE,
        V_RC_GIVING__SUMMARY.RC_GIVING__PREVIOUS_AMOUNT PREVIOUS_AMOUNT,
        V_RC_GIVING__SUMMARY.RC_GIVING__PREVIOUS_YEAR PREVIOUS_YEAR
  FROM V_ACCOUNT
  JOIN V_RC_GIVING__SUMMARY ON V_ACCOUNT.ID = V_RC_GIVING__SUMMARY.RC_GIVING__ACCOUNT
  JOIN V_CONTACT AS V_CONTACT_P ON V_ACCOUNT.RC_BIOS__PREFERRED_CONTACT = V_CONTACT_P.ID
  LEFT JOIN V_CONTACT AS V_CONTACT_S ON CONTACT_SECONDARY_GUID(V_ACCOUNT.ID) = V_CONTACT_S.ID
  LEFT JOIN S_PREFERRED_ADDRESS_BILLING ON S_PREFERRED_ADDRESS_BILLING.RC_BIOS__ACCOUNT = V_ACCOUNT.ID
 WHERE V_RC_GIVING__SUMMARY.RC_GIVING__ACTIVITY_TYPE = 'MEMBERSHIP' 
   AND V_RC_GIVING__SUMMARY.RC_GIVING__IS_MOST_RECENT = 'TRUE'
   AND V_RC_GIVING__SUMMARY.RC_GIVING__IS_LIFETIME = 'FALSE'
   -- CUSTOMIZED FOR CLIENT 
   AND V_RC_GIVING__SUMMARY.RC_GIVING__AFFILIATION = 'GROUP 1';