DROP FUNCTION IF EXISTS GET_TABLE_NAME;
CREATE FUNCTION `GET_TABLE_NAME`(OBJECT_NAME_IN VARCHAR(255)) RETURNS VARCHAR(255) CHARSET LATIN1
BEGIN
     DECLARE TABLE_NAME_OUT VARCHAR(255);
     SET TABLE_NAME_OUT = 
       (SELECT TABLE_NAME FROM RJ_OBJECT WHERE OBJECT_NAME = OBJECT_NAME_IN); 
	RETURN TABLE_NAME_OUT;
END;
