DROP FUNCTION IF EXISTS GET_OBJECT_NAME;
CREATE FUNCTION GET_OBJECT_NAME(TABLE_NAME_IN VARCHAR(255)) RETURNS VARCHAR(255) CHARSET LATIN1
BEGIN
     DECLARE OBJECT_NAME_OUT VARCHAR(255);
     SET OBJECT_NAME_OUT = 
       (SELECT OBJECT_NAME FROM RJ_OBJECT WHERE TABLE_NAME = TABLE_NAME_IN); 
	RETURN OBJECT_NAME_OUT;
END;
