DROP FUNCTION IF EXISTS GET_FIELD_LABEL;
CREATE FUNCTION `GET_FIELD_LABEL`(FIELD_NAME_IN VARCHAR(255), TABLE_NAME_IN VARCHAR(255)) RETURNS varchar(255) CHARSET latin1
BEGIN
     DECLARE FIELD_LABEL_OUT VARCHAR(255);
     SET FIELD_LABEL_OUT = 
       (SELECT CONCAT('`', LABEL, '`') FROM RJ_FIELD WHERE TABLE_NAME = TABLE_NAME_IN AND FIELD_NAME = FIELD_NAME_IN); 
	RETURN FIELD_LABEL_OUT;
END;
