DROP FUNCTION IF EXISTS analytics_demo.GET_FIELD_NAME;
CREATE FUNCTION analytics_demo.`GET_FIELD_NAME`(COLUMN_NAME_IN VARCHAR(255), TABLE_NAME_IN VARCHAR(255)) RETURNS varchar(255) CHARSET latin1
BEGIN
     DECLARE FIELD_NAME_OUT VARCHAR(255);
     SET FIELD_NAME_OUT = 
       (SELECT FIELD_NAME FROM RJ_FIELD WHERE COLUMN_NAME = COLUMN_NAME_IN AND TABLE_NAME = TABLE_NAME_IN); 
	RETURN FIELD_NAME_OUT;
END;