DROP PROCEDURE IF EXISTS CREATE_UNIVERSE_GIVING_SUMMARY_ANNUAL_LIFETIME;
CREATE PROCEDURE CREATE_UNIVERSE_GIVING_SUMMARY_ANNUAL_LIFETIME()
BEGIN 

SET @FIELD_LIST = (select 
    group_concat(concat(
       CASE WHEN TABLE_NAME = 'rc_giving__summary' THEN 'v_rc_GIVING__SUMMARY'
          ELSE TABLE_NAME
        END
        , 
        '.', COLUMN_NAME, ' as ', ifnull(UNIVERSE_FIELD_NAME_OVERRIDE, UNIVERSE_FIELD_NAME)))
from RD_UNIDEF_GIVING_SUMMARY_ANNUAL_LIFETIME
where included = 'True'
and UNIVERSE_name = 'U_GIVING_SUMMARY_ANNUAL_LIFETIME'
order by RD_UNIDEF_GIVING_SUMMARY_ANNUAL_LIFETIME.orderby, record_number
);

SET @1 ='create or replace VIEW U_GIVING_SUMMARY_ANNUAL_LIFETIME as select ';
SET @2 = left(@FIELD_LIST, char_length(@FIELD_LIST) - 1);
SET @3 =' from v_rc_GIVING__SUMMARY where rc_giving__activity_type = \'Membership\' and rc_giving__is_lifetime = \'True\'';

SET @UNIVERSE_DEF = (SELECT CONCAT(@1, @2, @3) AS UNIVERSE_DEF);

PREPARE UNIVERSE_DEF_STMT FROM @UNIVERSE_DEF;

EXECUTE UNIVERSE_DEF_STMT;

DEALLOCATE PREPARE UNIVERSE_DEF_STMT;

END;