CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_closedate', 'closedate');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_closedatetime', 'rc_giving__close_date_time');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_amount', 'amount');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_rc_giving_amount', 'rc_giving__giving_amount');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_rc_giving_current_amount', 'rc_giving__current_giving_amou');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_fiscalyear', 'fiscalyear');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_recordtype', 'recordtypeid');
CALL create_index_if_not_exists(get_table_name('opportunity'), 'ix_opportunity_parent', 'rc_giving__parent');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_gau', 'RC_GIVING__gau');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_source_code', 'RC_GIVING__source_code');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_source_code_partial', 'RC_GIVING__source_code_partial');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_affiliation', 'RC_GIVING__affiliation');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_channel', 'RC_GIVING__channel');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_campaign_type', 'RC_GIVING__campaign_type');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_appeal_segment', 'RC_GIVING__appeal_segment');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_effort', 'RC_GIVING__effort');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_solicitation_type', 'RC_GIVING__solicitation_type');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_support_designation', 'RC_GIVING__support_designation');
CALL create_index_if_not_exists(get_table_name('campaign'), 'ix_campaign_segment', 'RC_GIVING__segment');
CALL create_index_if_not_exists(get_table_name('rc_giving__gau__c'), 'ix_rc_giv_gau_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('rc_giving__gau__c'), 'ix_rc_giving__gau_parent', 'rc_giving__parent');
CALL create_index_if_not_exists(get_table_name('rc_giving__opportunity_allocation__c'), 'ix_rc_giv_allocation_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('rc_giving__opportunity_credit__c'), 'ix_rc_giv_credit_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('rc_giving__opportunity_credit__c'), 'ix_rc_giv_credit_amount', 'rc_giving__amount');
CALL create_index_if_not_exists(get_table_name('rc_giving__opportunity_credit__c'), 'ix_rc_giv_credit_opp_close_date', get_column_name('RC_GIVING__OPPORTUNITY_CLOSE_Date__c', 'RC_GIVING__SUMMARY'));
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_IS_SUSTAINING_GIVER', 'RC_GIVING__IS_SUSTAINING_GIVER');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_IS_SHOPPER', 'RC_GIVING__IS_SHOPPER');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_IS_MAJOR_GIVER', 'RC_GIVING__IS_MAJOR_GIVER');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_IS_LIFETIME', 'RC_GIVING__IS_LIFETIME');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_IS_HISTORICAL', 'RC_GIVING__IS_HISTORICAL');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_IS_ANNUAL', 'RC_GIVING__IS_ANNUAL');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_HISTORICAL_YEAR', 'RC_GIVING__HISTORICAL_YEAR');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_GIVING_LEVEL_STATUS', 'RC_GIVING__GIVING_LEVEL_STATUS');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_CURRENT_YEAR', 'RC_GIVING__CURRENT_YEAR');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_AFFILIATION', 'RC_GIVING__AFFILIATION');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_ACTIVITY_TYPE', 'RC_GIVING__ACTIVITY_TYPE');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_CURRENT_ANNUAL_AMOUNT', get_column_name('RC_GIVING__CURRENT_ANNUAL_AMOUNT__C', 'RC_GIVING__SUMMARY'));
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_CURRENT_AMOUNT', 'RC_GIVING__CURRENT_AMOUNT');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_CURRENT_CLOSED_AMOUNT', get_column_name('RC_GIVING__CURRENT_CLOSED_AMOUNT__C', 'RC_GIVING__SUMMARY'));
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_PREVIOUS_AMOUNT', 'RC_GIVING__PREVIOUS_AMOUNT');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_MOST_RECENT_GIVING', 'RC_GIVING__MOST_RECENT_GIVING');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_FIRST_PAYMENT_DATE', 'RC_GIVING__FIRST_PAYMENT_DATE');
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_FIRST_CLOSED_PAYMENT', get_column_name('rC_Giving__First_Closed_Payment_Date__c', 'RC_GIVING__SUMMARY'));
CALL create_index_if_not_exists(get_table_name('rc_giving__summary__c'), 'ix_rc_giv_summ_CURRENT_EXPIRATION', 'RC_GIVING__CURRENT_EXPIRATION');
CALL create_index_if_not_exists(get_table_name('opportunitylineitem'), 'ix_opplineitem_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('opportunitylineitem'), 'ix_opplineitem_SERVICEDATE', 'SERVICEDATE');
CALL create_index_if_not_exists(get_table_name('opportunitylineitem'), 'ix_opplineitem_DELIVERY_STATUE', 'RC_GIVING__DELIVERY_STATUS');
CALL create_index_if_not_exists(get_table_name('product2'), 'ix_product_del_archive_flags', 'DELETE_FLAG, RC_GIVING__ARCHIVE_FLAG');
CALL create_index_if_not_exists(get_table_name('pricebook2'), 'ix_pricebook_del_archive_flags', 'DELETE_FLAG');
CALL create_index_if_not_exists(get_table_name('pricebookentry'), 'ix_pricebookentry_del_archive_flags', 'DELETE_FLAG');
CALL create_index_if_not_exists(get_table_name('rc_giving__package_item__c'), 'ix_rc_giv_package_item_del_archive_flags', 'DELETE_FLAG');